CREATE TABLE ENERGY_DATA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    DATE_INFO TEXT NOT NULL,
    PROGRAM TEXT NOT NULL,
    DEGREE INT NOT NULL,
    ROTATIONS INT NOT NULL,
    KWH REAL NOT NULL
);

INSERT INTO ENERGY_DATA ( DATE_INFO, PROGRAM, DEGREE, ROTATIONS, KWH) VALUES ( "2020-02-27", "Baumwolle", 40, 1400, 0.37 );
