CREATE TABLE ENERGY_DATA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    DATE_INFO TEXT NOT NULL,
    PROGRAM TEXT NOT NULL,
    KWH REAL NOT NULL
);

INSERT INTO ENERGY_DATA ( DATE_INFO, PROGRAM, KWH) VALUES ( "2020-02-27", "Waschen", 0.37 );
INSERT INTO ENERGY_DATA ( DATE_INFO, PROGRAM, KWH) VALUES ( "2020-01-26", "Waschen2", 0.373 );