CREATE TABLE ENERGY_DATA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    DATE_INFO TEXT NOT NULL,
    PROGRAM TEXT NOT NULL,
    DEGREE INT NOT NULL,
    ROTATIONS INT NOT NULL,
    INTENSIVE INT NOT NULL,
    KWH REAL NOT NULL
);

INSERT INTO ENERGY_DATA ( DATE_INFO, PROGRAM, DEGREE, ROTATIONS, INTENSIVE, KWH) VALUES ( "2020-10-01", "Baumwolle", 40, 1400, 1, 0.34 );
INSERT INTO ENERGY_DATA ( DATE_INFO, PROGRAM, DEGREE, ROTATIONS, INTENSIVE, KWH) VALUES ( "2020-10-02", "Baumwolle", 60, 1400, 1, 0.38 );
INSERT INTO ENERGY_DATA ( DATE_INFO, PROGRAM, DEGREE, ROTATIONS, INTENSIVE, KWH ) VALUES ( "2020-10-04", "Jeans", 40, 1000, 0, 0.59 );
INSERT INTO ENERGY_DATA ( DATE_INFO, PROGRAM, DEGREE, ROTATIONS, INTENSIVE, KWH ) VALUES ( "2020-10-25", "Unterwäsche", 60, 1000, 0, 0.72 );
